//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Service.FaultContracts
{
	/// <summary>
	/// Data Contract Class - AuthenticationFailure
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://CareManagement.Model/2012/User", Name = "AuthenticationFailure")]
	public partial class AuthenticationFailure 
	{
		private string message;
		
		[WcfSerialization::DataMember(Name = "Message", IsRequired = true, Order = 0)]
		public string Message
		{
		  get { return message; }
		  set { message = value; }
		}				
	}
}

