
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AccountRequestMessage
	/// </summary>
	[WCF::MessageContract(WrapperName = "AccountRequestMessage", WrapperNamespace = "http://CareManagement.Model/2012/Accounts")] 
	public partial class AccountRequestMessage
	{
		private Infrastructure.Model.Account.Account account;
	 	private Infrastructure.Model.Security.UserLogin user;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Accounts", Name = "Account")]
		public Infrastructure.Model.Account.Account Account
		{
			get { return account; }
			set { account = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Accounts", Name = "User")]
		public Infrastructure.Model.Security.UserLogin User
		{
			get { return user; }
			set { user = value; }
		}
	}
}

