
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AccountIdRequestMessage
	/// </summary>
	[WCF::MessageContract(WrapperName = "AccountIdRequestMessage", WrapperNamespace = "http://caremanagement.model/2012/account")] 
	public partial class AccountIdRequestMessage
	{
		private int accountId;
	 	private Infrastructure.Model.Security.UserLogin user;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Medical", Name = "AccountId")]
		public int AccountId
		{
			get { return accountId; }
			set { accountId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Medical", Name = "User")]
		public Infrastructure.Model.Security.UserLogin User
		{
			get { return user; }
			set { user = value; }
		}
	}
}

