
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AuthorizationRequestIdMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class AuthorizationRequestIdMessage
	{
		private int authorizationRequestId;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Insurance", Name = "AuthorizationRequestId")]
		public int AuthorizationRequestId
		{
			get { return authorizationRequestId; }
			set { authorizationRequestId = value; }
		}
	}
}

