
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AuthorizationRequestRequestMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class AuthorizationRequestRequestMessage
	{
		private Infrastructure.Model.Insurance.AuthorizationRequest authorizationRequest;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Insurance", Name = "AuthorizationRequest")]
		public Infrastructure.Model.Insurance.AuthorizationRequest AuthorizationRequest
		{
			get { return authorizationRequest; }
			set { authorizationRequest = value; }
		}
	}
}

