
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AuthorizationRequestsMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class AuthorizationRequestsMessage
	{
		private System.Collections.Generic.List<Infrastructure.Model.Insurance.AuthorizationRequest> authorizationRequests;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Insurance", Name = "AuthorizationRequests")]
		public System.Collections.Generic.List<Infrastructure.Model.Insurance.AuthorizationRequest> AuthorizationRequests
		{
			get { return authorizationRequests; }
			set { authorizationRequests = value; }
		}
	}
}

