
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CreateUserRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class CreateUserRequest
	{
		private Service.DataContracts.NewUser request;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/User", Name = "Request")]
		public Service.DataContracts.NewUser Request
		{
			get { return request; }
			set { request = value; }
		}
	}
}

