
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - FacilityIdRequestMessage
	/// </summary>
	[WCF::MessageContract(WrapperName = "FacilityIdRequestMessage", WrapperNamespace = "http://CareManagement.Model/2012/Medical")] 
	public partial class FacilityIdRequestMessage
	{
		private int facilityId;
	 	private Infrastructure.Model.Security.UserLogin user;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Medical", Name = "FacilityId")]
		public int FacilityId
		{
			get { return facilityId; }
			set { facilityId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Medical", Name = "User")]
		public Infrastructure.Model.Security.UserLogin User
		{
			get { return user; }
			set { user = value; }
		}
	}
}

