
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - InsurerRequestMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class InsurerRequestMessage
	{
		private Infrastructure.Model.Insurance.Insurer insurer;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Insurance", Name = "Insurer")]
		public Infrastructure.Model.Insurance.Insurer Insurer
		{
			get { return insurer; }
			set { insurer = value; }
		}
	}
}

