
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - InsurersMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class InsurersMessage
	{
		private System.Collections.Generic.List<Infrastructure.Model.Insurance.Insurer> insurers;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Insurance", Name = "Insurers")]
		public System.Collections.Generic.List<Infrastructure.Model.Insurance.Insurer> Insurers
		{
			get { return insurers; }
			set { insurers = value; }
		}
	}
}

