
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - InsurerIdRequestMessage
	/// </summary>
	[WCF::MessageContract(WrapperName = "InsurerIdRequestMessage", WrapperNamespace = "http://CareManagement.Model/2012/Insurance")] 
	public partial class InsurerIdRequestMessage
	{
		private int insurerId;
	 	private Infrastructure.Model.Security.UserLogin user;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Insurance", Name = "InsurerId")]
		public int InsurerId
		{
			get { return insurerId; }
			set { insurerId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Insurance", Name = "User")]
		public Infrastructure.Model.Security.UserLogin User
		{
			get { return user; }
			set { user = value; }
		}
	}
}

