
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - MedicationsMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class MedicationsMessage
	{
		private System.Collections.Generic.List<Infrastructure.Model.Prescription.Medication> medications;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Prescription", Name = "Medications")]
		public System.Collections.Generic.List<Infrastructure.Model.Prescription.Medication> Medications
		{
			get { return medications; }
			set { medications = value; }
		}
	}
}

