
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - PrescriptionPickupIdMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class PrescriptionPickupIdMessage
	{
		private int prescriptionPickupId;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Prescription", Name = "PrescriptionPickupId")]
		public int PrescriptionPickupId
		{
			get { return prescriptionPickupId; }
			set { prescriptionPickupId = value; }
		}
	}
}

