
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - PrescriptionPickupsMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class PrescriptionPickupsMessage
	{
		private System.Collections.Generic.List<Infrastructure.Model.Prescription.PrescriptionPickup> prescriptionPickups;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Prescription", Name = "PrescriptionPickups")]
		public System.Collections.Generic.List<Infrastructure.Model.Prescription.PrescriptionPickup> PrescriptionPickups
		{
			get { return prescriptionPickups; }
			set { prescriptionPickups = value; }
		}
	}
}

