
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - PrescriptionPickupMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class PrescriptionPickupMessage
	{
		private Infrastructure.Model.Prescription.PrescriptionPickup prescriptionPickup;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Prescription", Name = "PrescriptionPickup")]
		public Infrastructure.Model.Prescription.PrescriptionPickup PrescriptionPickup
		{
			get { return prescriptionPickup; }
			set { prescriptionPickup = value; }
		}
	}
}

