
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ProviderRequestMessage
	/// </summary>
	[WCF::MessageContract(WrapperName = "ProviderRequestMessage", WrapperNamespace = "http://CareManagement.Model/2012/Medical")] 
	public partial class ProviderRequestMessage
	{
		private Infrastructure.Model.Medical.Provider provider;
	 	private Infrastructure.Model.Security.UserLogin user;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Medical", Name = "Provider")]
		public Infrastructure.Model.Medical.Provider Provider
		{
			get { return provider; }
			set { provider = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/Medical", Name = "User")]
		public Infrastructure.Model.Security.UserLogin User
		{
			get { return user; }
			set { user = value; }
		}
	}
}

