
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.MessageContracts
{
	/// <summary>
	/// Service Contract Class - UserCreatedResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class UserCreatedResponse
	{
		private Service.DataContracts.UserCreated response;
	 		
		[WCF::MessageBodyMember(Namespace = "http://CareManagement.Model/2012/User", Name = "Response")]
		public Service.DataContracts.UserCreated Response
		{
			get { return response; }
			set { response = value; }
		}
	}
}

