//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Client.PrescriptionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medication", Namespace="http://schemas.datacontract.org/2004/07/Infrastructure.Model.Prescription")]
    [System.SerializableAttribute()]
    public partial class Medication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CurrentVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Service.Client.PrescriptionServiceReference.DosageUnits> DosageUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CurrentVersion {
            get {
                return this.CurrentVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionField, value) != true)) {
                    this.CurrentVersionField = value;
                    this.RaisePropertyChanged("CurrentVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Service.Client.PrescriptionServiceReference.DosageUnits> DosageUnits {
            get {
                return this.DosageUnitsField;
            }
            set {
                if ((this.DosageUnitsField.Equals(value) != true)) {
                    this.DosageUnitsField = value;
                    this.RaisePropertyChanged("DosageUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DosageUnits", Namespace="http://schemas.datacontract.org/2004/07/Infrastructure.Model.Prescription")]
    public enum DosageUnits : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tablet = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Milliliter = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Milligram = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Teaspoon = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tablespoon = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLogin", Namespace="http://schemas.datacontract.org/2004/07/Infrastructure.Model.Security")]
    [System.SerializableAttribute()]
    public partial class UserLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrescriptionPickup", Namespace="http://schemas.datacontract.org/2004/07/Infrastructure.Model.Prescription")]
    [System.SerializableAttribute()]
    public partial class PrescriptionPickup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset AppointmentDateTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CurrentVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MedicationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset AppointmentDateTimeUtc {
            get {
                return this.AppointmentDateTimeUtcField;
            }
            set {
                if ((this.AppointmentDateTimeUtcField.Equals(value) != true)) {
                    this.AppointmentDateTimeUtcField = value;
                    this.RaisePropertyChanged("AppointmentDateTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CurrentVersion {
            get {
                return this.CurrentVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionField, value) != true)) {
                    this.CurrentVersionField = value;
                    this.RaisePropertyChanged("CurrentVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MedicationId {
            get {
                return this.MedicationIdField;
            }
            set {
                if ((this.MedicationIdField.Equals(value) != true)) {
                    this.MedicationIdField = value;
                    this.RaisePropertyChanged("MedicationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicationIdMessage", Namespace="http://CareManagement.Model/2012/Prescription")]
    [System.SerializableAttribute()]
    public partial class MedicationIdMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MedicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Service.Client.PrescriptionServiceReference.UserLogin UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MedicationId {
            get {
                return this.MedicationIdField;
            }
            set {
                if ((this.MedicationIdField.Equals(value) != true)) {
                    this.MedicationIdField = value;
                    this.RaisePropertyChanged("MedicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Client.PrescriptionServiceReference.UserLogin User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountIdMessage", Namespace="http://CareManagement.Model/2012/Accounts")]
    [System.SerializableAttribute()]
    public partial class AccountIdMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Service.Client.PrescriptionServiceReference.UserLogin UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Client.PrescriptionServiceReference.UserLogin User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrescriptionPickupIdMessage", Namespace="http://CareManagement.Model/2012/Prescription")]
    [System.SerializableAttribute()]
    public partial class PrescriptionPickupIdMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrescriptionPickupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Service.Client.PrescriptionServiceReference.UserLogin UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrescriptionPickupId {
            get {
                return this.PrescriptionPickupIdField;
            }
            set {
                if ((this.PrescriptionPickupIdField.Equals(value) != true)) {
                    this.PrescriptionPickupIdField = value;
                    this.RaisePropertyChanged("PrescriptionPickupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Client.PrescriptionServiceReference.UserLogin User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CareManagement.Model/2012/Prescription", ConfigurationName="PrescriptionServiceReference.PrescriptionContract")]
    public interface PrescriptionContract {
        
        // CODEGEN: Generating message contract since the operation AddMedication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AddMedication", ReplyAction="addmedication")]
        Service.Client.PrescriptionServiceReference.AddMedicationResponse AddMedication(Service.Client.PrescriptionServiceReference.MedicationRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation DeleteMedication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="DeleteMedication", ReplyAction="deletemedication")]
        Service.Client.PrescriptionServiceReference.DeleteMedicationResponse DeleteMedication(Service.Client.PrescriptionServiceReference.MedicationRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation UpdateMedication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="UpdateMedication", ReplyAction="updatemedication")]
        Service.Client.PrescriptionServiceReference.UpdateMedicationResponse UpdateMedication(Service.Client.PrescriptionServiceReference.MedicationRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation GetMedication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetMedication", ReplyAction="getmedication")]
        Service.Client.PrescriptionServiceReference.MedicationMessage GetMedication(Service.Client.PrescriptionServiceReference.MedicationIdMessage1 request);
        
        // CODEGEN: Generating message contract since the operation GetMedicationsByAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetMedicationsByAccount", ReplyAction="getmedicationsbyaccount")]
        Service.Client.PrescriptionServiceReference.MedicationsMessage GetMedicationsByAccount(Service.Client.PrescriptionServiceReference.AccountIdMessage1 request);
        
        // CODEGEN: Generating message contract since the operation AddPrescriptionPickup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AddPrescriptionPickup", ReplyAction="addprescriptionpickup")]
        Service.Client.PrescriptionServiceReference.AddPrescriptionPickupResponse AddPrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation DeletePrescriptionPickup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="DeletePrescriptionPickup", ReplyAction="deleteprescriptionpickup")]
        Service.Client.PrescriptionServiceReference.DeletePrescriptionPickupResponse DeletePrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation UpdatePrescriptionPickup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="UpdatePrescriptionPickup", ReplyAction="updateprescriptionpickup")]
        Service.Client.PrescriptionServiceReference.UpdatePrescriptionPickupResponse UpdatePrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation GetPrescriptionPickup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPrescriptionPickup", ReplyAction="getprescriptionpickup")]
        Service.Client.PrescriptionServiceReference.PrescriptionPickupMessage GetPrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupIdMessage1 request);
        
        // CODEGEN: Generating message contract since the operation GetPrescriptionPickupsByMedication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPrescriptionPickupsByMedication", ReplyAction="getprescriptionpickupsbymedication")]
        Service.Client.PrescriptionServiceReference.PrescriptionPickupsMessage GetPrescriptionPickupsByMedication(Service.Client.PrescriptionServiceReference.MedicationIdMessage1 request);
        
        // CODEGEN: Generating message contract since the operation GetPrescriptionPickupsByAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPrescriptionPickupsByAccount", ReplyAction="getprescriptionpickupsbyaccount")]
        Service.Client.PrescriptionServiceReference.PrescriptionPickupsMessage GetPrescriptionPickupsByAccount(Service.Client.PrescriptionServiceReference.AccountIdMessage1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MedicationRequestMessage", WrapperNamespace="http://CareManagement.Model/2012/Prescription", IsWrapped=true)]
    public partial class MedicationRequestMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.Medication Medication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=1)]
        public Service.Client.PrescriptionServiceReference.UserLogin User;
        
        public MedicationRequestMessage() {
        }
        
        public MedicationRequestMessage(Service.Client.PrescriptionServiceReference.Medication Medication, Service.Client.PrescriptionServiceReference.UserLogin User) {
            this.Medication = Medication;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMedicationResponse {
        
        public AddMedicationResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMedicationResponse {
        
        public DeleteMedicationResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMedicationResponse {
        
        public UpdateMedicationResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MedicationIdMessage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.MedicationIdMessage MedicationIdMessage;
        
        public MedicationIdMessage1() {
        }
        
        public MedicationIdMessage1(Service.Client.PrescriptionServiceReference.MedicationIdMessage MedicationIdMessage) {
            this.MedicationIdMessage = MedicationIdMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MedicationMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.Medication Medication;
        
        public MedicationMessage() {
        }
        
        public MedicationMessage(Service.Client.PrescriptionServiceReference.Medication Medication) {
            this.Medication = Medication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountIdMessage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Accounts", Order=0)]
        public Service.Client.PrescriptionServiceReference.AccountIdMessage AccountIdMessage;
        
        public AccountIdMessage1() {
        }
        
        public AccountIdMessage1(Service.Client.PrescriptionServiceReference.AccountIdMessage AccountIdMessage) {
            this.AccountIdMessage = AccountIdMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MedicationsMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.Medication[] Medications;
        
        public MedicationsMessage() {
        }
        
        public MedicationsMessage(Service.Client.PrescriptionServiceReference.Medication[] Medications) {
            this.Medications = Medications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrescriptionPickupRequestMessage", WrapperNamespace="http://CareManagement.Model/2012/Prescription", IsWrapped=true)]
    public partial class PrescriptionPickupRequestMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.PrescriptionPickup PrescriptionPickup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=1)]
        public Service.Client.PrescriptionServiceReference.UserLogin User;
        
        public PrescriptionPickupRequestMessage() {
        }
        
        public PrescriptionPickupRequestMessage(Service.Client.PrescriptionServiceReference.PrescriptionPickup PrescriptionPickup, Service.Client.PrescriptionServiceReference.UserLogin User) {
            this.PrescriptionPickup = PrescriptionPickup;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPrescriptionPickupResponse {
        
        public AddPrescriptionPickupResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePrescriptionPickupResponse {
        
        public DeletePrescriptionPickupResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrescriptionPickupResponse {
        
        public UpdatePrescriptionPickupResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrescriptionPickupIdMessage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.PrescriptionPickupIdMessage PrescriptionPickupIdMessage;
        
        public PrescriptionPickupIdMessage1() {
        }
        
        public PrescriptionPickupIdMessage1(Service.Client.PrescriptionServiceReference.PrescriptionPickupIdMessage PrescriptionPickupIdMessage) {
            this.PrescriptionPickupIdMessage = PrescriptionPickupIdMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrescriptionPickupMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.PrescriptionPickup PrescriptionPickup;
        
        public PrescriptionPickupMessage() {
        }
        
        public PrescriptionPickupMessage(Service.Client.PrescriptionServiceReference.PrescriptionPickup PrescriptionPickup) {
            this.PrescriptionPickup = PrescriptionPickup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrescriptionPickupsMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Prescription", Order=0)]
        public Service.Client.PrescriptionServiceReference.PrescriptionPickup[] PrescriptionPickups;
        
        public PrescriptionPickupsMessage() {
        }
        
        public PrescriptionPickupsMessage(Service.Client.PrescriptionServiceReference.PrescriptionPickup[] PrescriptionPickups) {
            this.PrescriptionPickups = PrescriptionPickups;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrescriptionContractChannel : Service.Client.PrescriptionServiceReference.PrescriptionContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrescriptionContractClient : System.ServiceModel.ClientBase<Service.Client.PrescriptionServiceReference.PrescriptionContract>, Service.Client.PrescriptionServiceReference.PrescriptionContract {
        
        public PrescriptionContractClient() {
        }
        
        public PrescriptionContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrescriptionContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrescriptionContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrescriptionContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.AddMedicationResponse Service.Client.PrescriptionServiceReference.PrescriptionContract.AddMedication(Service.Client.PrescriptionServiceReference.MedicationRequestMessage request) {
            return base.Channel.AddMedication(request);
        }
        
        public void AddMedication(Service.Client.PrescriptionServiceReference.Medication Medication, Service.Client.PrescriptionServiceReference.UserLogin User) {
            Service.Client.PrescriptionServiceReference.MedicationRequestMessage inValue = new Service.Client.PrescriptionServiceReference.MedicationRequestMessage();
            inValue.Medication = Medication;
            inValue.User = User;
            Service.Client.PrescriptionServiceReference.AddMedicationResponse retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).AddMedication(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.DeleteMedicationResponse Service.Client.PrescriptionServiceReference.PrescriptionContract.DeleteMedication(Service.Client.PrescriptionServiceReference.MedicationRequestMessage request) {
            return base.Channel.DeleteMedication(request);
        }
        
        public void DeleteMedication(Service.Client.PrescriptionServiceReference.Medication Medication, Service.Client.PrescriptionServiceReference.UserLogin User) {
            Service.Client.PrescriptionServiceReference.MedicationRequestMessage inValue = new Service.Client.PrescriptionServiceReference.MedicationRequestMessage();
            inValue.Medication = Medication;
            inValue.User = User;
            Service.Client.PrescriptionServiceReference.DeleteMedicationResponse retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).DeleteMedication(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.UpdateMedicationResponse Service.Client.PrescriptionServiceReference.PrescriptionContract.UpdateMedication(Service.Client.PrescriptionServiceReference.MedicationRequestMessage request) {
            return base.Channel.UpdateMedication(request);
        }
        
        public void UpdateMedication(Service.Client.PrescriptionServiceReference.Medication Medication, Service.Client.PrescriptionServiceReference.UserLogin User) {
            Service.Client.PrescriptionServiceReference.MedicationRequestMessage inValue = new Service.Client.PrescriptionServiceReference.MedicationRequestMessage();
            inValue.Medication = Medication;
            inValue.User = User;
            Service.Client.PrescriptionServiceReference.UpdateMedicationResponse retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).UpdateMedication(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.MedicationMessage Service.Client.PrescriptionServiceReference.PrescriptionContract.GetMedication(Service.Client.PrescriptionServiceReference.MedicationIdMessage1 request) {
            return base.Channel.GetMedication(request);
        }
        
        public Service.Client.PrescriptionServiceReference.Medication GetMedication(Service.Client.PrescriptionServiceReference.MedicationIdMessage MedicationIdMessage) {
            Service.Client.PrescriptionServiceReference.MedicationIdMessage1 inValue = new Service.Client.PrescriptionServiceReference.MedicationIdMessage1();
            inValue.MedicationIdMessage = MedicationIdMessage;
            Service.Client.PrescriptionServiceReference.MedicationMessage retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).GetMedication(inValue);
            return retVal.Medication;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.MedicationsMessage Service.Client.PrescriptionServiceReference.PrescriptionContract.GetMedicationsByAccount(Service.Client.PrescriptionServiceReference.AccountIdMessage1 request) {
            return base.Channel.GetMedicationsByAccount(request);
        }
        
        public Service.Client.PrescriptionServiceReference.Medication[] GetMedicationsByAccount(Service.Client.PrescriptionServiceReference.AccountIdMessage AccountIdMessage) {
            Service.Client.PrescriptionServiceReference.AccountIdMessage1 inValue = new Service.Client.PrescriptionServiceReference.AccountIdMessage1();
            inValue.AccountIdMessage = AccountIdMessage;
            Service.Client.PrescriptionServiceReference.MedicationsMessage retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).GetMedicationsByAccount(inValue);
            return retVal.Medications;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.AddPrescriptionPickupResponse Service.Client.PrescriptionServiceReference.PrescriptionContract.AddPrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage request) {
            return base.Channel.AddPrescriptionPickup(request);
        }
        
        public void AddPrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickup PrescriptionPickup, Service.Client.PrescriptionServiceReference.UserLogin User) {
            Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage inValue = new Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage();
            inValue.PrescriptionPickup = PrescriptionPickup;
            inValue.User = User;
            Service.Client.PrescriptionServiceReference.AddPrescriptionPickupResponse retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).AddPrescriptionPickup(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.DeletePrescriptionPickupResponse Service.Client.PrescriptionServiceReference.PrescriptionContract.DeletePrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage request) {
            return base.Channel.DeletePrescriptionPickup(request);
        }
        
        public void DeletePrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickup PrescriptionPickup, Service.Client.PrescriptionServiceReference.UserLogin User) {
            Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage inValue = new Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage();
            inValue.PrescriptionPickup = PrescriptionPickup;
            inValue.User = User;
            Service.Client.PrescriptionServiceReference.DeletePrescriptionPickupResponse retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).DeletePrescriptionPickup(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.UpdatePrescriptionPickupResponse Service.Client.PrescriptionServiceReference.PrescriptionContract.UpdatePrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage request) {
            return base.Channel.UpdatePrescriptionPickup(request);
        }
        
        public void UpdatePrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickup PrescriptionPickup, Service.Client.PrescriptionServiceReference.UserLogin User) {
            Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage inValue = new Service.Client.PrescriptionServiceReference.PrescriptionPickupRequestMessage();
            inValue.PrescriptionPickup = PrescriptionPickup;
            inValue.User = User;
            Service.Client.PrescriptionServiceReference.UpdatePrescriptionPickupResponse retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).UpdatePrescriptionPickup(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.PrescriptionPickupMessage Service.Client.PrescriptionServiceReference.PrescriptionContract.GetPrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupIdMessage1 request) {
            return base.Channel.GetPrescriptionPickup(request);
        }
        
        public Service.Client.PrescriptionServiceReference.PrescriptionPickup GetPrescriptionPickup(Service.Client.PrescriptionServiceReference.PrescriptionPickupIdMessage PrescriptionPickupIdMessage) {
            Service.Client.PrescriptionServiceReference.PrescriptionPickupIdMessage1 inValue = new Service.Client.PrescriptionServiceReference.PrescriptionPickupIdMessage1();
            inValue.PrescriptionPickupIdMessage = PrescriptionPickupIdMessage;
            Service.Client.PrescriptionServiceReference.PrescriptionPickupMessage retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).GetPrescriptionPickup(inValue);
            return retVal.PrescriptionPickup;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.PrescriptionPickupsMessage Service.Client.PrescriptionServiceReference.PrescriptionContract.GetPrescriptionPickupsByMedication(Service.Client.PrescriptionServiceReference.MedicationIdMessage1 request) {
            return base.Channel.GetPrescriptionPickupsByMedication(request);
        }
        
        public Service.Client.PrescriptionServiceReference.PrescriptionPickup[] GetPrescriptionPickupsByMedication(Service.Client.PrescriptionServiceReference.MedicationIdMessage MedicationIdMessage) {
            Service.Client.PrescriptionServiceReference.MedicationIdMessage1 inValue = new Service.Client.PrescriptionServiceReference.MedicationIdMessage1();
            inValue.MedicationIdMessage = MedicationIdMessage;
            Service.Client.PrescriptionServiceReference.PrescriptionPickupsMessage retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).GetPrescriptionPickupsByMedication(inValue);
            return retVal.PrescriptionPickups;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.PrescriptionServiceReference.PrescriptionPickupsMessage Service.Client.PrescriptionServiceReference.PrescriptionContract.GetPrescriptionPickupsByAccount(Service.Client.PrescriptionServiceReference.AccountIdMessage1 request) {
            return base.Channel.GetPrescriptionPickupsByAccount(request);
        }
        
        public Service.Client.PrescriptionServiceReference.PrescriptionPickup[] GetPrescriptionPickupsByAccount(Service.Client.PrescriptionServiceReference.AccountIdMessage AccountIdMessage) {
            Service.Client.PrescriptionServiceReference.AccountIdMessage1 inValue = new Service.Client.PrescriptionServiceReference.AccountIdMessage1();
            inValue.AccountIdMessage = AccountIdMessage;
            Service.Client.PrescriptionServiceReference.PrescriptionPickupsMessage retVal = ((Service.Client.PrescriptionServiceReference.PrescriptionContract)(this)).GetPrescriptionPickupsByAccount(inValue);
            return retVal.PrescriptionPickups;
        }
    }
}
