//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/Infrastructure.Model.Account")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CurrentVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CurrentVersion {
            get {
                return this.CurrentVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionField, value) != true)) {
                    this.CurrentVersionField = value;
                    this.RaisePropertyChanged("CurrentVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIdString {
            get {
                return this.UserIdStringField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdStringField, value) != true)) {
                    this.UserIdStringField = value;
                    this.RaisePropertyChanged("UserIdString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLogin", Namespace="http://schemas.datacontract.org/2004/07/Infrastructure.Model.Security")]
    [System.SerializableAttribute()]
    public partial class UserLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountIdMessage", Namespace="http://CareManagement.Model/2012/Accounts")]
    [System.SerializableAttribute()]
    public partial class AccountIdMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Service.Client.ServiceReference1.UserLogin UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Client.ServiceReference1.UserLogin User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CareManagement.Model/2012/Accounts", ConfigurationName="ServiceReference1.AccountContract")]
    public interface AccountContract {
        
        // CODEGEN: Generating message contract since the operation AddAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AddAccount", ReplyAction="addaccount")]
        Service.Client.ServiceReference1.AddAccountResponse AddAccount(Service.Client.ServiceReference1.AddAccountRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation DeleteAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="DeleteAccount", ReplyAction="deleteaccount")]
        Service.Client.ServiceReference1.DeleteAccountResponse DeleteAccount(Service.Client.ServiceReference1.AccountRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation UpdateAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="UpdateAccount", ReplyAction="updateaccount")]
        Service.Client.ServiceReference1.UpdateAccountResponse UpdateAccount(Service.Client.ServiceReference1.AccountRequestMessage request);
        
        // CODEGEN: Generating message contract since the operation GetAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetAccount", ReplyAction="getaccount")]
        Service.Client.ServiceReference1.AccountMessage GetAccount(Service.Client.ServiceReference1.AccountIdMessage1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddAccountRequestMessage", WrapperNamespace="http://CareManagement.Model/2012/Accounts", IsWrapped=true)]
    public partial class AddAccountRequestMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Accounts", Order=0)]
        public Service.Client.ServiceReference1.Account Account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Accounts", Order=1)]
        public string Password;
        
        public AddAccountRequestMessage() {
        }
        
        public AddAccountRequestMessage(Service.Client.ServiceReference1.Account Account, string Password) {
            this.Account = Account;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountResponse {
        
        public AddAccountResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountRequestMessage", WrapperNamespace="http://CareManagement.Model/2012/Accounts", IsWrapped=true)]
    public partial class AccountRequestMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Accounts", Order=0)]
        public Service.Client.ServiceReference1.Account Account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Accounts", Order=1)]
        public Service.Client.ServiceReference1.UserLogin User;
        
        public AccountRequestMessage() {
        }
        
        public AccountRequestMessage(Service.Client.ServiceReference1.Account Account, Service.Client.ServiceReference1.UserLogin User) {
            this.Account = Account;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAccountResponse {
        
        public DeleteAccountResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAccountResponse {
        
        public UpdateAccountResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountIdMessage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Accounts", Order=0)]
        public Service.Client.ServiceReference1.AccountIdMessage AccountIdMessage;
        
        public AccountIdMessage1() {
        }
        
        public AccountIdMessage1(Service.Client.ServiceReference1.AccountIdMessage AccountIdMessage) {
            this.AccountIdMessage = AccountIdMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CareManagement.Model/2012/Accounts", Order=0)]
        public Service.Client.ServiceReference1.Account Account;
        
        public AccountMessage() {
        }
        
        public AccountMessage(Service.Client.ServiceReference1.Account Account) {
            this.Account = Account;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountContractChannel : Service.Client.ServiceReference1.AccountContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountContractClient : System.ServiceModel.ClientBase<Service.Client.ServiceReference1.AccountContract>, Service.Client.ServiceReference1.AccountContract {
        
        public AccountContractClient() {
        }
        
        public AccountContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.ServiceReference1.AddAccountResponse Service.Client.ServiceReference1.AccountContract.AddAccount(Service.Client.ServiceReference1.AddAccountRequestMessage request) {
            return base.Channel.AddAccount(request);
        }
        
        public void AddAccount(Service.Client.ServiceReference1.Account Account, string Password) {
            Service.Client.ServiceReference1.AddAccountRequestMessage inValue = new Service.Client.ServiceReference1.AddAccountRequestMessage();
            inValue.Account = Account;
            inValue.Password = Password;
            Service.Client.ServiceReference1.AddAccountResponse retVal = ((Service.Client.ServiceReference1.AccountContract)(this)).AddAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.ServiceReference1.DeleteAccountResponse Service.Client.ServiceReference1.AccountContract.DeleteAccount(Service.Client.ServiceReference1.AccountRequestMessage request) {
            return base.Channel.DeleteAccount(request);
        }
        
        public void DeleteAccount(Service.Client.ServiceReference1.Account Account, Service.Client.ServiceReference1.UserLogin User) {
            Service.Client.ServiceReference1.AccountRequestMessage inValue = new Service.Client.ServiceReference1.AccountRequestMessage();
            inValue.Account = Account;
            inValue.User = User;
            Service.Client.ServiceReference1.DeleteAccountResponse retVal = ((Service.Client.ServiceReference1.AccountContract)(this)).DeleteAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.ServiceReference1.UpdateAccountResponse Service.Client.ServiceReference1.AccountContract.UpdateAccount(Service.Client.ServiceReference1.AccountRequestMessage request) {
            return base.Channel.UpdateAccount(request);
        }
        
        public void UpdateAccount(Service.Client.ServiceReference1.Account Account, Service.Client.ServiceReference1.UserLogin User) {
            Service.Client.ServiceReference1.AccountRequestMessage inValue = new Service.Client.ServiceReference1.AccountRequestMessage();
            inValue.Account = Account;
            inValue.User = User;
            Service.Client.ServiceReference1.UpdateAccountResponse retVal = ((Service.Client.ServiceReference1.AccountContract)(this)).UpdateAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.Client.ServiceReference1.AccountMessage Service.Client.ServiceReference1.AccountContract.GetAccount(Service.Client.ServiceReference1.AccountIdMessage1 request) {
            return base.Channel.GetAccount(request);
        }
        
        public Service.Client.ServiceReference1.Account GetAccount(Service.Client.ServiceReference1.AccountIdMessage AccountIdMessage) {
            Service.Client.ServiceReference1.AccountIdMessage1 inValue = new Service.Client.ServiceReference1.AccountIdMessage1();
            inValue.AccountIdMessage = AccountIdMessage;
            Service.Client.ServiceReference1.AccountMessage retVal = ((Service.Client.ServiceReference1.AccountContract)(this)).GetAccount(inValue);
            return retVal.Account;
        }
    }
}
