//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Service.DataContracts
{
	/// <summary>
	/// Data Contract Class - AuthenticationResponse
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://CareManagement.Model/2012/User", Name = "AuthenticationResponse")]
	public partial class AuthenticationResponse 
	{
		private System.Guid sessionToken;
		
		[WcfSerialization::DataMember(Name = "SessionToken", IsRequired = true, Order = 0)]
		public System.Guid SessionToken
		{
		  get { return sessionToken; }
		  set { sessionToken = value; }
		}				
	}
}

