//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Service.DataContracts
{
	/// <summary>
	/// Data Contract Class - UserCreated
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://CareManagement.Model/2012/User", Name = "UserCreated")]
	public partial class UserCreated 
	{
		private int userId;
		
		[WcfSerialization::DataMember(Name = "UserId", IsRequired = true, Order = 0)]
		public int UserId
		{
		  get { return userId; }
		  set { userId = value; }
		}				
	}
}

