//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Service.ServiceImplementation
{	
	/// <summary>
	/// Service Class - AccountService
	/// </summary>
	[WCF::ServiceBehavior(Name = "AccountService", 
		Namespace = "http://CareManagement.Model/2012/Accounts", 
		InstanceContextMode = WCF::InstanceContextMode.PerSession, 
		ConcurrencyMode = WCF::ConcurrencyMode.Single )]
	public abstract class AccountServiceBase : Service.ServiceContracts.IAccountContract
	{
		#region AccountContract Members

		public virtual void AddAccount(Service.MessageContracts.AddAccountMessage request)
		{
			
		}

		public virtual void DeleteAccount(Service.MessageContracts.AccountMessage request)
		{
			
		}

		public virtual void UpdateAccount(Service.MessageContracts.AccountMessage request)
		{
			
		}

		public virtual Service.MessageContracts.AccountMessage GetAccount(Service.MessageContracts.AccountIdMessage request)
		{
			return null;
		}

		#endregion		
		
	}
	
	public partial class AccountService : AccountServiceBase
	{
	}
	
}

