//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Service.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - User
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://CareManagement.Model/2012/User", Name = "User", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IUser 
	{
		[WCF::FaultContract(typeof(Service.FaultContracts.AuthenticationFailure))]
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "authenticate", ReplyAction = "authenticate", ProtectionLevel = ProtectionLevel.None)]
		Service.MessageContracts.AuthenticateResponse Authenticate(Service.MessageContracts.AuthenticateRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "create", ProtectionLevel = ProtectionLevel.None)]
		Service.MessageContracts.UserCreatedResponse Create(Service.MessageContracts.CreateUserRequest request);
		
	}
}

